# Generated by Django 5.0.3 on 2024-05-30 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_userprofile_height_userprofile_interest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='religions',
            name='caste',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='religion',
        ),
        migrations.AddField(
            model_name='caste',
            name='religion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.religions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='caste',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.caste'),
            preserve_default=False,
        ),
    ]
